### ISSUE TITLE
Gradle plugin doesn't work inside afterEvaluate

### ISSUE THREAD

**Issue by coderanger** [GoogleCloudPlatform/artifact-registry-maven-tools#45]
The following snippet fails:

```groovy
afterEvaluate {
    publishing {
        // Other stuff like:
        // publications { }
      repositories {
          maven {
              name = "..."
              url "artifactregistry://us-west1-maven.pkg.dev/wallspice/..."
          }
      }
   }
}
```

with the error:

```
* What went wrong:
Execution failed for task ':native_lib:publishDebugPublicationTo[our repo]Repository'.
> Failed to publish publication 'debug' to repository '[our repo]'
   > Not a supported repository protocol 'artifactregistry': valid protocols are [file, http, https, gcs, s3, sftp]
```

Basically it looks like the plugin just isn't loaded at all. Was easy to fix by moving the repo settings out of `afterEvaluate` since nothing there varies at runtime but was very confusing for a bit so wanted to document it for others.

**Comment by lindsayismith** [comment]
Thanks for the report!  I'm not sure if it should work here or not, if any Gradle experts know, please add to this bug.  I'm closing this as you had a workaround, and we'll keep the bug here for further users.

**Comment by loosebazooka** [comment]
The issues arises because this: https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/master/artifactregistry-gradle-plugin/src/main/java/com/google/cloud/artifactregistry/gradle/plugin/ArtifactRegistryGradlePlugin.java#L125 is bound before the repository is configured (because of the after evaluate). There might be away to use whenObjectAdded or some sort of callback to handle this to configure all current and future added repositories.
