### ISSUE TITLE
Configuration Cache compatibility with Gradle 8.1+

### ISSUE THREAD

**Issue by Naitbit** [GoogleCloudPlatform/artifact-registry-maven-tools#85]
When trying to use artifactregistry-gradle-plugin:2.2.0 with Configuartion Cache Gradle 8.1 it errors out with:

1 problem was found storing the configuration cache.
- Plugin 'com.google.cloud.artifactregistry.gradle-plugin': external process started 'gcloud config config-helper --format=json(credential)'
  See https://docs.gradle.org/8.1-rc-3/userguide/configuration_cache.html#config_cache:requirements:external_processes

**Comment by Naitbit** [comment]
Still happens with 
artifactregistry-gradle-plugin:2.2.1
Gradle 8.1.1

**Comment by Naitbit** [comment]
Pushed my fork of ArtifactRegistry to our git source code, it's just ~13KB.

**Comment by bjoernmayer** [comment]
Any news on this? Or workarounds?

**Comment by Naitbit** [comment]
Well I did build my branch locally and put .jar as dependency. It fixed CC complain, but I'm not vouching for my accidental fork.

**Comment by jjohannes** [comment]
As workaround, you can apply the plugin conditionally only for publishing builds. It's not very nice but works. This means:

- For normal developing work (compiling, testing, ...) you can use the configuration cache
- The publishing build (on CI) needs to run with `--no-configuration-cache` (otherwise build fails with unsupported repository type as the plugin is not active).

```
if (!serviceOf<BuildFeatures>().configurationCache.active.get()) {
    apply(plugin = "com.google.cloud.artifactregistry.gradle-plugin")
}
```

In real project: https://github.com/hashgraph/hedera-services/blob/8432c100bf4ac9d6a417dac2d9b544d4dc9f6380/build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.platform-maven-publish.gradle.kts#L25-L30

**Comment by bjoernmayer** [comment]
Won't work for us. We are using the plugin mainly to handle the access to the artifact maven repo. 
I am considering to create a PR for this repo with a fix, that is based on Naitbits fork

**Comment by bjoernmayer** [comment]
I've created a new Gradle Plugin:
https://github.com/bjoernmayer/artifactregistry-gradle

**Comment by prouland** [comment]
Any idea of which version will bring this fix ? :)

**Comment by galan** [comment]
Issue still occours. Tested with gradle 8.10.x and 9.x
@yihanzhen Why has this been closed? @bjoernmayer How does your fix solve this?

Still struggeling with this issue
```
1 problem was found storing the configuration cache.
- Plugin class 'com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin': external process started 'gcloud config config-helper --format=json(credential)'
  See https://docs.gradle.org/8.10.2/userguide/configuration_cache.html#config_cache:requirements:external_processes
```

Trying to bisect the issue, it seems to be broken since 2.0.1, so this is the last working version:

```
initscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.0.0"
  }
}
apply plugin: com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin
```
Sidenote, why is 2.2.2 the latest version in the repository? Something is off in the [documentation](https://cloud.google.com/artifact-registry/docs/java/authentication#helper-gradle). (2.2.5 is referenced)
https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/artifactregistry/artifactregistry-gradle-plugin/ (only has 2.0.0-2.2.2)
